plugins {
    id 'java'
}

group = 'org.springframework'
version = '5.3.39'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    implementation(project(":spring-beans"))
    implementation(project(":spring-core"))
    implementation(project(":spring-context"))
    implementation(project(":spring-aop"))
    implementation(project(":spring-tx"))
    implementation(project(":spring-jdbc"))
    implementation("org.aspectj:aspectjweaver")
    implementation("com.alibaba:druid:1.2.20")
    runtimeOnly("mysql:mysql-connector-java:8.0.33")
}

test {
    useJUnitPlatform()
}
